spring:
  resources:
    cache:
        period: 31556926
    static-locations: file:./src/main/sencha
  jpa:
    show-sql: true

server:
  port: 8443
  httpPort: 8088
  compression:
    enabled: false

management:
  security:
    enabled: true
  endpoint:
    metrics:
      enabled: true
        #    filter:
        #      enabled: true
        #  health:
        #    sensitive: false

logging:
  level:
    org.springframework: INFO
    org.apache: INFO
    ch: INFO
    org.springframework.data: DEBUG
    org.springframework.data.mongodb.core.MongoDbUtils: INFO
    com.grinnotech: DEBUG
