info:
  app.name: "@project.name@"
  app.description: "@project.description@"
  app.version: "@project.version@"
  build.artifact: "@project.artifactId@"
  build.time: "@build.timestamp@"

app:
  url: http://localhost:8085
  rememberme-cookie-key: patients
  rememberme-cookie-valid-in-days: 31
  default-email-sender: no-reply@starter.com
  login-lock-attempts: 10
  login-lock-minutes: 30

mongodb:
  uri: mongodb://localhost/patients?w=1&wtimeoutMS=0&journal=true

security:
  ignored:
    - none

spring:
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
  
  resources:
    cache-period: 31556926
  
  mvc:
    favicon:
      enabled: false

  mail:
    host: localhost    

  async:
    core-pool-size: 2
    max-pool-size: 20
    queue-capacity: 200
    thread-name-prefix: patients-async-executor

  main:
    banner-mode: log 


server:
  port: 8088
  session:
    timeout: 480
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt     
  use-forward-headers: true

logging:
  level:
    org.springframework: INFO
    org.mongodb: INFO
    org.apache: INFO
    com.grinno: DEBUG
  file: ./app.log

endpoints:
  metrics:
    enabled: false
    filter:
      enabled: false

management:
  add-application-context-header: false