CREATE ROLE keycloak WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'keycloak';

-- CREATE ROLE patient_registry WITH
--   LOGIN
--   NOSUPERUSER
--   INHERIT
--   NOCREATEDB
--   NOCREATEROLE
--   NOREPLICATION
--   ENCRYPTED PASSWORD 'patient_registry';

CREATE SCHEMA keycloak AUTHORIZATION keycloak;

