server:
    port: 9083

spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/patient-registry
        username: keycloak
        password: keycloak
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        hibernate:
            ddl-auto: create

keycloak:
    server:
        contextPath: /auth
        adminUser:
            username: admin
            password: admin
        realmImportFile: keycloak-realm.json
